background                = "#090909"
background-alpha          = 0.99
text                      = "#D5D0C6"
border                    = "#66625B"
border-alpha              = 1.0
border-width              = 1
scrim                     = "#050505"
scrim-alpha               = 0.72
selected-background       = "#2F0508"
selected-background-alpha = 0.9
selected-text             = "#E1DBCF"
selected-border           = "#B51D24"
selected-border-alpha     = 1.0
selected-border-width     = "0 0 0 2"
